name: Integrate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: true
      matrix:
        php: [ "8.0", "8.1", "8.2" ]

    runs-on: ubuntu-latest
    name: PHP@${{ matrix.php }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Composer configuration
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Detect coding standards violations
        run: composer run-script lint

      - name: Perform static analysis
        run: composer run-script analyse

      - name: Execute unit tests
        run: composer run-script test
